#!/bin/bash

# Compared to default start-octant script, this removes the option to set an
# override for the default namespace when Octant is opened.

exec /opt/kubernetes/bin/octant --disable-open-browser --listener-addr 127.0.0.1:10086 --accepted-hosts $SESSION_NAMESPACE-console.$INGRESS_DOMAIN
