apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - name: 80-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
